language: go
dist: bionic
services:
  - docker
go:
  - 1.13.5
env:
  global:
    - CONTAINER_TAG=v1.17.0-test
    - secure: MD9RiXb66Cnx8dZuVB9kxs625z+V2ckE85q8QYPXIbDSbf7cr52nzUEeT/5xqIiqeefbrtcN5c+9D52LUP7XXUai0RFGI1fP5QAadbodIVCQjAV/v6ko3ab+IRQH0GG1T0C5srAAx8VbxnFqwxgKhzkpvaTHD/W7d4xFbVSV3m+SPMFg/kIk4lbqoKtt6alcW31zqhtFUKDWcIU24ZfjlRj3UqJZX3afQaOcx37/M/qgG3HGeszdR2V43SENbk1mDV/exTgOtqV1DkeEVQM6MHZlC0gxk1oy5P4/Fo4REGL3Uo3C2HLYMxSkza6kpaVTv1yYcVjHYpzXDDNrfKMPkBxQK0uJw4jDzdQBzm2M7+abqmyz47JpD/4xa6TKl/n9CucsYgnRa97VFGLBid6Qi0mTI8jQnwZkBc6L57RnCg9kRvgb8Tu2OtwFaD+Mt6jp/ySUqFEdYTo2sTJAOPNmMS++TdzT2i8zyZLUXcLSiofgSiXlAU+KJVP0+c9ypnbwPS1MWvZWASOIGWRydOiHwZoHg9WpTHCGmqG7UPJrxU6ZhQrLkTZb6HZjo1G9pTCoGNd0yTY1Yr3q0tOhkILoLG/ZviMgQROjm5n1BvByySlMjBExvSKSxjgs5ddBiM9B9K0ku3GGVh84Ldzw4a+4PI/X9M7nsQTd7xqIgFobw7g=
    - secure: I98Jc3Q37j/3x8X4rtK1tR0PARQuBTUuhSuQs+VgLna6Bg1X7z8TD/rcmccmLJjR+M/LVMKTTST8W2o3zTLJBfjE01lwFYbjpXFfyKeEYZWrnVewpaVKBeHO5RUXxhpdWckS0QOsEWn1VBdJCLz+71inWA1gdOF/ZrJJHsAF/Nh4TnvTOICYw0a3M/4MZWr86ZVpWCRI/aMaWDrm/tJcB05xZqGS960dSw0oXHe3FFMNX/yJMVTjxUIemWeXcg6Y8c7JOKY5IOQDPfMLjn/DB19bCfpkp+frV1nI/6YvSYPECL6M+FEiG6zeET6YPNtXIfq6w5pZBoB4QpTDv5EgDpbIuaXwLjetOIybQvq8dYWoSlKz2DJ+8XV5KXvknqKY5t2HaVs7a3wPBAKJ+5arcmqsRcA6zF8aacJs5IUfc3VYpd/VTop92PsvvOi6h4Rtxm35/ZQ/58lAi6n0RJyNWfkjis2KnJU+h4DtKv6XRVZS0dxtKunYRPDLOO6MqldJMevbFH5JwZYrBXrzcZIHWsRKxMSGy1MOMavuESxpmTIZBan/RyN0uwTnvnqr8jo9W6MBgYMR4Sj1aVa1WGP+BVebQob1OeJZUgJM/AA28q94qE79FzvVVN382IF/akAbDPBHoRGHGZJ8jNuUVRjiHXMzZH7ZozodpB5DbPp5tyU=
    - secure: BIrhFXjwKHyJfbDhWjG1ELGOmpH+EycKSXlDAYYzr55DF5i6vOM/0zGfya1zoUR+VqhoS9arewafbCpQ4lyKymDexHIC1KXoCamZGTzy34vaTTF5o08as8OR2dcOEu75hYj6XihEKQwirrJ9a6BlhdsBwaGiww9nYTR0miP864FAFZnnzcQZNZnnsus7XPtEKurU3cfMQ8ZC3ClreMCkwjj+SBip5bmXaLzweYl6n2tPXdxhAqSVMsHa/dwU1yf7ujQh1IbFDX6AL/7mIU4jnypdDDFnIy5JbdRfqjPujOof8UW1OWxcZbOJUusIcnf6S9oC9pnqpJEj08OZkztIg+fKtOyiqDH8hPqvRC0e8x3QLZhPMCT256aSfVDa+lGbHVlJb6R6yvVgBC0aFm/fUjqcRfPxuYJBAn3sg2EglQTWfscsnhVBVjir0xZiilIfFs+kmUOsGEtnEdUH2JYl/C7scCGM0jHXiXtPccNrjAfCttvMckmw9JlJKvGnN5Tfmk+wi4OxoDSQwHI0emTi1HhGSnLKys6PCXb0R0WnT+V2dUCsF5fzszxxk/DpSWLE4VsC7Got7JPdAKxV/DkyEJk5pRjBfE9GiqhM/QEabx6Z/HmGgJ9w72Lx5Ih/pjCEfyMsQ7eVSPkZ6FqoCscexQ4MdgdL6y5clFjY2Wcsfd4=
before_install:
  - openssl aes-256-cbc -K $encrypted_6cd5e44028b6_key -iv $encrypted_6cd5e44028b6_iv -in key.enc -out key -d
script:
  - docker build . -f kube-scheduler/Dockerfile -t storageos/kube-scheduler:latest
deploy:
  - provider: script
    script: bash publish.sh
    skip_cleanup: true
    on:
      tags: true
